<?php

    $employee = $block->getAllEmployee();
?>


<form method="post" action="<?= $block->saveEmployee() ?>">
    <label for="first_name">First Name: 
        <input type="text" name="first_name" />
    </label>
    <label for="last_name">Last Name: 
        <input type="text" name="last_name" />
    </label>
    <label for="first_name">Email: 
        <input type="email" name="email_id" />
    </label>
    <button type="submit" >Submit</button>
</form>


<?php if(count($employee) > 0): ?>

<table border="1">
    <tr>
        <th>Employee ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
    </tr>

    <?php foreach($employee as $emp): ?>
    <tr>
        <td><?= $emp->getData("employee_id") ?></td>
        <td><?= $emp->getData("first_name") ?></td>
        <td><?= $emp->getData("last_name") ?></td>
        <td><?= $emp->getData("email_id") ?></td>
    </tr>
    <?php endforeach; ?>
</table>

<?php endif; ?>
