<fieldset id="payment_form_stripe_payments" class="stripe-payments standard-form admin__fieldset" style="display:none;">
  <div class="fieldset indent">
    <?php echo $block->getLayout()->createBlock('StripeIntegration\Payments\Block\Adminhtml\SavedPaymentMethods')->toHtml(); ?>
  </div>
</fieldset>

<script type="text/javascript">
  require(['domReady!', 'jquery', 'mage/mage'], function(domReady, $)
  {
    setTimeout(stripe.disableCardValidation, 5000);
    var dataForm = $('#payment_form_stripe_payments');
    dataForm.mage('validation', {});
  });
</script>
