<?php

$methods = $this->getSavedPaymentMethods();

if (empty($methods)): ?>
<div class="message info empty">
  <span><?php echo $block->escapeHtml(__('You do not have any saved payment methods.')); ?></span>
</div>
<?php else: ?>
  <div class="table-wrapper stripe-payments saved-payment-methods">
    <table class="data table table-order-items history saved-cards" id="my-orders-table">
      <caption class="table-caption"><?php echo $block->escapeHtml(__('Saved Payment Methods')); ?></caption>
      <thead>
        <tr>
          <th scope="col" class="col cards">
            <?php echo $block->escapeHtml(__('Payment Method')); ?>
          </th>
          <th scope="col" class="col actions"><?php echo $block->escapeHtml(__('Actions')); ?></th>
        </tr>
      </thead>
      <tbody>
  <?php foreach ($methods as $type => $methodList): ?>
    <?php foreach ($methodList as $method): ?>
      <tr>
        <td data-th="Payment Method" class="col brand saved-payment-method-name">
          <img src="<?php echo $block->getIcon($method); ?>" height="32" class="saved-payment-method-icon" />
          <label><?php echo $block->getLabel($method); ?></label>
        </td>
        <td data-th="Actions" class="col actions">
          <a href="<?php echo $block->getUrl('*/*/*', ['delete' => $method->id]); ?>" class="stripe-payments delete-method"
            onclick="return confirm('<?php echo __("Are you sure you want to delete this payment method?"); ?>')">
            <?php echo $block->escapeHtml(__('Delete')); ?>
          </a>
        </td>
      </tr>
    <?php endforeach; ?>
  <?php endforeach; ?>
      </tbody>
    </table>
  </div>
<?php endif; ?>
